### PR TITLE
refer to specific versions of IL-RFCs

### PR DESCRIPTION
**Pull request by michielbdejong**
Continuation of https://github.com/w3c/webpayments/pull/246

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
SpecRef has a way of handling versioning. My plan is to integrate this into our more deep SpecRef integration as described in https://github.com/interledger/rfcs/issues/389

Example:
```json
  "interledger-protocol": {
    "title": "The Interledger Protocol",
    "href": "https://interledger.org/rfcs/0003-interledger-protocol/",
    "status": "IL RFC",
    "publisher": "Interledger Community",
    "versions": {
        "draft-9": {
          "title": "The Interledger Protocol [Draft 9]",
          "href": "https://interledger.org/rfcs/0003-interledger-protocol/draft-9.html",
          "status": "IL RFC",
          "publisher": "Interledger Community"
        }
    }  
  }
```
Then in the spec we update the references from `[[!interledger-protocol]]` to `[[!interledger-protocol-draft-9]]`.

If you want to add the latest versions to this document using the correct syntax then feel free, we'll try and automate this and add the older versions in resolving https://github.com/interledger/rfcs/issues/389

**Review by adrianhopebailie — COMMENTED** [review]
Use correct versioning syntax

**Review by adrianhopebailie — DISMISSED** [review]
Use correct versioning syntax

**Comment by michielbdejong** [comment]
@adrianhopebailie bump

**Comment by michielbdejong** [comment]
closing because of https://github.com/w3c/webpayments/pull/248#issuecomment-372602943

**Pull request closed without merging**
